### ISSUE TITLE
Add OSX to Travis builds

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#588]
We currently don't test or release builds for OSX on conda. Travis supports an OSX environment simply by adding the "os" to the build matrix.

**Comment by snorfalorpagus** [comment]
I was under the impression that you could only use Linux with the free service? I may be wrong.

**Comment by jetuk** [comment]
https://travis-ci.org/pywr/pywr/builds/330302941

**Comment by snorfalorpagus** [comment]
I stand corrected.

The other issue is that there is often a massive backlog on macOS builds on Travis:

https://www.traviscistatus.com/

**Comment by jetuk** [comment]
That backlog only seems to have happened in the last day or so.

**Comment by snorfalorpagus** [comment]
You should remove the `BUILD_DOC=1` environment variable from the macOS build.

**Comment by jetuk** [comment]
What's the best way to do that?

**Comment by snorfalorpagus** [comment]
I think we need to put both os/env in the matrix, like this:

```
matrix:
  - os: linux
    env: CONDA_PY=27
  - os: linux
    env: CONDA_PY=34
  - os: linux
    env: CONDA_PY=36 BUILD_DOC=1
  - os: osx
    env: CONDA_PY=36
```
